//BLOG
export const FRONTEND_GET_BLOGS = 'BLOG/FRONTEND_GET_BLOGS'
// export const FRONTEND_CREATE_COMMENT = 'BLOG/FRONTEND_CREATE_COMMENT'


//PROFILE
export const GET_PROFILE_MENU = 'PROFILE/GET_PROFILE_MENU'
export const CHANGE_PROFILE_MENU = 'PROFILE/CHANGE_PROFILE_MENU'
export const GET_CANDIDATE = 'PROFILE/GET_CANDIDATE'


//PROFILE MESSAGE
export const GET_MESSAGES = 'PROFILE/GET_MESSAGES'
export const SEND_MESSAGE = 'PROFILE/SEND_MESSAGE'
export const DELETE_MESSAGE = 'PROFILE/DELETE_MESSAGE'
// export const EDIT_MESSAGE = 'PROFILE/EDIT_MESSAGE'

//TEACHER PROFILE INFORMATION
export const GET_TEACHER = 'PROFILE/GET_TEACHER'
export const TEACHER_CREATE_EDUCATION = 'TEACHER_PROFILE/TEACHER_CREATE_EDUCATION'
export const TEACHER_DELETE_EDUCATION = 'TEACHER_PROFILE/TEACHER_DELETE_EDUCATION'
export const TEACHER_CREATE_CERTIFICATE = 'TEACHER_PROFILE/TEACHER_CREATE_CERTIFICATE'
export const TEACHER_DELETE_CERTIFICATE = 'TEACHER_PROFILE/TEACHER_DELETE_CERTIFICATE'
export const TEACHER_CREATE_WORK_EXPERIENCE = 'TEACHER_PROFILE/TEACHER_CREATE_WORK_EXPERIENCE'
export const TEACHER_DELETE_WORK_EXPERIENCE = 'TEACHER_PROFILE/TEACHER_DELETE_WORK_EXPERIENCE'
export const TEACHER_SET_LANGUAGE_OF_INSTRUCTION = 'TEACHER_PROFILE/SET_LANGUAGE_OF_INSTRUCTION'
export const TEACHER_UPDATE_LANGUAGE_OF_INSTRUCTION = 'TEACHER_PROFILE/UPDATE_LANGUAGE_OF_INSTRUCTION'
export const TEACHER_CREATE_ADDRESS = 'TEACHER/TEACHER_CREATE_ADDRESS'
// export const TEACHER_UPDATE_ADDRESS = 'TEACHER/TEACHER_UPDATE_ADDRESS'
export const TEACHER_CREATE_PHONE = 'TEACHER/TEACHER_CREATE_PHONE'
export const TEACHER_DELETE_PHONE = 'TEACHER/TEACHER_DELETE_PHONE'
export const TEACHER_CREATE_VIDEO = 'TEACHER/TEACHER_CREATE_VIDEO'
export const TEACHER_DELETE_VIDEO = 'TEACHER/TEACHER_DELETE_VIDEO'

//NOTIFICATIONS
export const CHECK_NOTIFICATION = 'TEACHER/CHECK_NOTIFICATION'
export const SET_NOTIFICATION = 'TEACHER/SET_NOTIFICATION'

//VIDEO CHAT
export const ROOM_USERS = 'VIDEO_CHAT/ROOM_USERS'
export const ROOM_CHAT = 'VIDEO_CHAT/ROOM_CHAT'
export const CREATE_ROOM_MESSAGE = 'VIDEO_CHAT/CREATE_ROOM_MESSAGE'
export const ROOM_VIDEO = 'VIDEO_CHAT/ROOM_VIDEO'
export const ROOM_USER = 'VIDEO_CHAT/ROOM_USER'

// FREE TIMES
export const CREATE_FREE_TIME = 'FREE_TIME/CREATE_FREE_TIME'
export const ALL_FREE_TIMES = 'FREE_TIME/ALL_FREE_TIMES'
export const DELETE_FREE_TIME = 'FREE_TIME/DELETE_FREE_TIME'
export const DELETE_CREATED_FREE_TIME = 'FREE_TIME/DELETE_CREATED_FREE_TIME'
export const SAVE_CREATED_TIMES = 'FREE_TIME/SAVE_CREATED_TIMES'

// LOADERS

export const SHOW_PROFILE_LOADER = 'LOADER/SHOW_PROFILE_LOADER'
export const HIDE_PROFILE_LOADER = 'LOADER/HIDE_PROFILE_LOADER'


// WINDOW MESSAGE FIELD
export const OPEN_WINDOW_MESSAGE_FIELD = 'MESSAGE/OPEN_WINDOW_MESSAGE_FIELD'
export const CLOSE_WINDOW_MESSAGE_FIELD = 'MESSAGE/CLOSE_WINDOW_MESSAGE_FIELD'
