//BLOG
export const FRONTEND_GET_BLOGS = 'BLOG/FRONTEND_GET_BLOGS'
export const FRONTEND_CREATE_COMMENT = 'BLOG/FRONTEND_CREATE_COMMENT'


//PROFILE
export const GET_PROFILE_MENU = 'PROFILE/GET_PROFILE_MENU'
export const CHANGE_PROFILE_MENU = 'PROFILE/CHANGE_PROFILE_MENU'
export const GET_CANDIDATE = 'PROFILE/GET_CANDIDATE'
